# Generated by Django 4.2.7 on 2024-01-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resumee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('education', models.TextField()),
                ('projects', models.TextField()),
                ('links', models.TextField()),
                ('languages', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.experience')),
            ],
        ),
    ]
